src/Najdah/UserBundle/Entity/User.php
<?php
// src/Najdah/UserBundle/Entity/User.php

namespace Najdah\UserBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use FOS\UserBundle\Entity\User as BaseUser;
use Symfony\Component\HttpFoundation\File\UploadedFile;

/**
 * User
 *
 * @ORM\Table()
 * @ORM\Entity(repositoryClass="Najdah\UserBundle\Repository\UserRepository")
 * @ORM\HasLifecycleCallbacks()
 */
class User extends BaseUser
{
    /**
     * @var integer
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    protected $id;

    /**
     * @var string
     *
     * @ORM\Column(name="matricule", type="string", length=50, nullable=true)
     */
    private $matricule;

    /**
     * @var string
     *
     * @ORM\Column(name="nom", type="string", length=100, nullable=true)
     */
    private $nom;

    /**
     * @var string
     *
     * @ORM\Column(name="adresse", type="string", length=255, nullable=true)
     */
    private $adresse;

    /**
     * @var string
     *
     * @ORM\Column(name="tel", type="string", length=20, nullable=true)
     */
    private $tel;

    /**
     * @var string
     *
     * @ORM\Column(name="type", type="string", length=1, nullable=true)
     */
    private $type;

    /**
     * @var string
     *
     * @ORM\Column(name="lastX", type="string", length=150, nullable=true)
     */
    private $lastX;

    /**
     * @var string
     *
     * @ORM\Column(name="lastY", type="string", length=150, nullable=true)
     */
    private $lastY;
    
    /**
     * @var string
     *
     * @ORM\Column(name="image", type="string", length=150, nullable=true)
     */
    private $image;

    private $file;

    /**
     * @ORM\ManyToOne(targetEntity="Najdah\AppBundle\Entity\Ville")
     * @ORM\JoinColumn(nullable=true)
     */
    private $ville;

    /**
     * Get id
     *
     * @return integer 
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set matricule
     *
     * @param string $matricule
     * @return User
     */
    public function setMatricule($matricule)
    {
        $this->matricule = $matricule;

        return $this;
    }

    /**
     * Get matricule
     *
     * @return string 
     */
    public function getMatricule()
    {
        return $this->matricule;
    }

    /**
     * Set nom
     *
     * @param string $nom
     * @return User
     */
    public function setNom($nom)
    {
        $this->nom = $nom;

        return $this;
    }

    /**
     * Get nom
     *
     * @return string 
     */
    public function getNom()
    {
        return $this->nom;
    }

    /**
     * Set adresse
     *
     * @param string $adresse
     * @return User
     */
    public function setAdresse($adresse)
    {
        $this->adresse = $adresse;

        return $this;
    }

    /**
     * Get adresse
     *
     * @return string 
     */
    public function getAdresse()
    {
        return $this->adresse;
    }

    /**
     * Set tel
     *
     * @param string $tel
     * @return User
     */
    public function setTel($tel)
    {
        $this->tel = $tel;

        return $this;
    }

    /**
     * Get tel
     *
     * @return string 
     */
    public function getTel()
    {
        return $this->tel;
    }

    /**
     * Set type
     *
     * @param string $type
     * @return User
     */
    public function setType($type)
    {
        $this->type = $type;

        return $this;
    }

    /**
     * Get type
     *
     * @return string 
     */
    public function getType()
    {
        return $this->type;
    }

    /**
     * Set lastX
     *
     * @param string $lastX
     * @return User
     */
    public function setLastX($lastX)
    {
        $this->lastX = $lastX;

        return $this;
    }

    /**
     * Get lastX
     *
     * @return string 
     */
    public function getLastX()
    {
        return $this->lastX;
    }

    /**
     * Set lastY
     *
     * @param string $lastY
     * @return User
     */
    public function setLastY($lastY)
    {
        $this->lastY = $lastY;

        return $this;
    }

    /**
     * Get lastY
     *
     * @return string 
     */
    public function getLastY()
    {
        return $this->lastY;
    }
    
    /**
     * @ORM\PrePersist()
     * @ORM\PreUpdate()
     */
    public function preUpload()
    {
        // Si jamais il n'y a pas de fichier (champ facultatif)
        if (null === $this->file) { return; }
        $this->image = $this->file->guessExtension();
    }
	
    /**
     * @ORM\PostPersist()
     * @ORM\PostUpdate()
     */
    public function upload()
    {
        // Si jamais il n'y a pas de fichier (champ facultatif)
        if (null === $this->file) { return; }

        $this->file->move( $this->getUploadRootDir(), $this->id.'.'.$this->image );
    }
	
    /**
    * @ORM\PreRemove()
    */
    public function preRemoveUpload()
    {
        $tempFile = $this->getUploadRootDir().'/'.$this->id.'.'.$this->image;;
        if (file_exists($tempFile)) {
                unlink($tempFile);
        }
    }

    public function getUploadDir()
    {
        // On retourne le chemin relatif vers l'image pour un navigateur
        return 'najdah/img/users';
    }
    
    protected function getUploadRootDir()
    {
        // On retourne le chemin relatif vers l'image pour notre code PHP
        return __DIR__.'/../../../../web/'.$this->getUploadDir();
    }
	
    public function getWebPath()
    {
        return $this->getUploadDir().'/'.$this->getId().'.'.$this->getImage();
    }

    /**
     * Set image
     *
     * @param string $image
     * @return User
     */
    public function setImage($image)
    {
        $this->image = $image;

        return $this;
    }

    /**
     * Get image
     *
     * @return string 
     */
    public function getImage()
    {
        return $this->image;
    }
    
    public function getFile()
    {
        return $this->file;
    }
	
    public function setFile(UploadedFile $file)
    {
        $this->file = $file;
    }

    /**
     * Set ville
     *
     * @param \Najdah\AppBundle\Entity\Ville $ville
     * @return User
     */
    public function setVille(\Najdah\AppBundle\Entity\Ville $ville = null)
    {
        $this->ville = $ville;

        return $this;
    }

    /**
     * Get ville
     *
     * @return \Najdah\AppBundle\Entity\Ville 
     */
    public function getVille()
    {
        return $this->ville;
    }
}

src/Najdah/UserBundle/Controller/UserController.php
<?php

namespace Najdah\UserBundle\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\Controller;

use Najdah\UserBundle\Entity\User;
use Najdah\UserBundle\Form\UserAjouterType;
use Najdah\UserBundle\Form\UserModifierType;

class UserController extends Controller
{
    public function indexAction($type_user)
    {   
        $var='';
        if($type_user=='Policier')  $var='l';
        else    $var='m';
        $users = $this->getDoctrine()
                        ->getManager()
                        ->getRepository('NajdahUserBundle:User')
                        ->findBy( array('type' => $var),array('nom' => 'asc') );
		
        if($users === null)
        {
            throw $this->createNotFoundException('Il faut ajouter un '.$type_user.' !!');
        }
        return $this->render('NajdahUserBundle:User:index.html.twig',array('users' => $users,'type_user' => $type_user));
    }
    
    public function afficherAction($type_user,$id)
    {
        $user = $this->getDoctrine()->getManager()->getRepository('NajdahUserBundle:User')->find($id);
        if($user === null)
        {
            throw $this->createNotFoundException('Ce '.$type_user.' n existe pas!!');
        }
        return $this->render('NajdahUserBundle:User:afficher.html.twig', array('user' => $user));
    }
    
    public function ajouterAction($type_user)
    {
        $user = new User;
        $form = $this->createForm(new UserAjouterType, $user);

        // La gestion d'un formulaire est particulière, mais l'idée est la suivante :
        $request = $this->get('request');
        if( $request->getMethod() == 'POST' )
        {
            $form->bind($request);
            if ($form->isValid()) 
            {
                $em = $this->getDoctrine()->getManager();
                //ici
                //$user->setUsername($user->getMatricule());
                $user->setEmail($user->getUsername()."@Najdah.com");
                $user->setEnabled(1);
                $user->setPlainPassword('irisi');
                if($type_user=='Policier')      $user->setType('l');
                else    $user->setType('m');
                $em->persist($user);
                $em->flush();

                $this->get('session')->getFlashBag()->add('notice', 'User bien enregistré');
                return $this->redirect( $this->generateUrl('user_index', array('type_user' => $type_user)) );
            }
        }
        // Si on n'est pas en POST, alors on affiche le formulaire
        return $this->render('NajdahUserBundle:User:ajouter.html.twig',array('type_user' => $type_user,'form' => $form->createView(),));
    }
    
    public function modifierAction($type_user,$id)
    {
        $user = $this->getDoctrine()->getManager()->getRepository('NajdahUserBundle:User')->find($id);
        if($user === null)
        {
            throw $this->createNotFoundException('Il faut ajouter un '.$type_user.' !!');
        }

        $form = $this->createForm(new UserModifierType, $user);

        $request = $this->get('request');
        if( $request->getMethod() == 'POST' )
        {
            $form->bind($request);
            if ($form->isValid()) {
                $em = $this->getDoctrine()->getManager();
                $em->persist($user);
                $em->flush();

                $this->get('session')->getFlashBag()->add('notice', 'User modifier');
                return $this->redirect($this->generateUrl('user_index', array('type_user' => $type_user)));
            }
        }
        return $this->render('NajdahUserBundle:User:modifier.html.twig',array('form' => $form->createView(),'user' => $user));
    }
        
    public function supprimerAction($type_user,$id)
    {
        $em = $this->getDoctrine()->getManager();
        $user = $em->getRepository('NajdahUserBundle:User')->find($id);
        if($user === null)
        {
            throw $this->createNotFoundException('Ce '.$type_user.' n existe pas!!');
        }
        $em->remove($user);
        $em->flush();
        $this->get('session')->getFlashBag()->add('notice', 'User supprimer');
        return $this->redirect($this->generateUrl('user_index', array('type_user' => $type_user)));
    }
    
    public function lastUserAction()
    {
        /*
        $user = $this->getUser();
        $request = $this->getRequest();
        $request->cookies->set('username',$user->getUsername() );
         */

        return $this->render('NajdahUserBundle:User:lastUser.html.twig');
    }
    
    public function rolesAction($type_user,$id)
    {   
        $user = $this->getDoctrine()->getManager()->getRepository('NajdahUserBundle:User')->find($id);
        if($user === null)
        {
            throw $this->createNotFoundException('Il faut ajouter un '.$type_user.' !!');
        }

        
        $request = $this->get('request');
        if( $request->getMethod() == 'POST' )
        {
            $em = $this->getDoctrine()->getManager();
            //ICI
            if ($this->get('security.context')->isGranted('ROLE_ADMIN_POLICIER')) {
                if ($request->request->get('ROLE_POLICIER')!="")     $user->addRole('ROLE_POLICIER');
                else        $user->removeRole('ROLE_POLICIER');
            }
            if ($this->get('security.context')->isGranted('ROLE_ADMIN_POMPIER')) {
                if ($request->request->get('ROLE_POMPIER')!="")     $user->addRole('ROLE_POMPIER');
                else        $user->removeRole('ROLE_POMPIER');
            }
            if ($this->get('security.context')->isGranted('ROLE_ADMIN')) {
                if ($request->request->get('ROLE_ADMIN_POLICIER')!="")     $user->addRole('ROLE_ADMIN_POLICIER');
                else        $user->removeRole('ROLE_ADMIN_POLICIER');
            }
            if ($this->get('security.context')->isGranted('ROLE_ADMIN')) {
                if ($request->request->get('ROLE_ADMIN_POMPIER')!="")     $user->addRole('ROLE_ADMIN_POMPIER');
                else        $user->removeRole('ROLE_ADMIN_POMPIER');
            }
            if ($this->get('security.context')->isGranted('ROLE_SUPER_ADMIN')) {
                if ($request->request->get('ROLE_ADMIN')!="")     $user->addRole('ROLE_ADMIN');
                else        $user->removeRole('ROLE_ADMIN');
            }
            if ($this->get('security.context')->isGranted('ROLE_SUPER_ADMIN')) {
                if ($request->request->get('ROLE_SUPER_ADMIN')!="")     $user->addRole('ROLE_SUPER_ADMIN');
                else        $user->removeRole('ROLE_SUPER_ADMIN');
            }

            
            
            $em->persist($user);
            $em->flush();

            $this->get('session')->getFlashBag()->add('notice', 'User modifier');
            return $this->redirect($this->generateUrl('user_index', array('type_user' => $type_user)));
        
        }
        return $this->render('NajdahUserBundle:User:roles.html.twig',array('type_user' => $type_user,'user' => $user));
    }
}

src/Najdah/UserBundle/Resources/views/User/afficher.html.twig
{# src/Najdah/UserBundle/Resources/views/User/ajouter.html.twig #}

{% extends "NajdahUserBundle::layout.html.twig" %}

{% block body_userBundle %}
    <h2>Afficher :</h2>
	
    {% include "NajdahUserBundle:User:formulaire.html.twig" %}
{% endblock %}

src/Najdah/UserBundle/Resources/views/User/ajouter.html.twig
{# src/Najdah/UserBundle/Resources/views/User/ajouter.html.twig #}

{% extends "NajdahUserBundle::layout.html.twig" %}

{% block menu_Policiers %}{% if type_user=='Policier' %}<span class="selected"></span>{% endif %}{% endblock %}
{% block menu_Pompiers %}{% if type_user=='Pompier' %}<span class="selected"></span>{% endif %}{% endblock %}
{% block menu_Policiers_active %}{% if type_user=='Policier' %}active{% endif %}{% endblock %}
{% block menu_Pompiers_active %}{% if type_user=='Pompier' %}active{% endif %}{% endblock %}

{% block body_userBundle %}
    <h2>Ajouter :</h2>
	
    {% include "NajdahUserBundle:User:formulaire.html.twig" %}
{% endblock %}

src/Najdah/UserBundle/Resources/views/User/formulaire.html.twig
{# src/Najdah/UserBundle/Resources/views/User/formulaire.html.twig #}

<div class="well">
	<form method="post" {{ form_enctype(form) }}>
		{{ form_widget(form) }}
		<input type="submit" class="btn btn-primary" />
	</form>
</div>

src/Najdah/UserBundle/Resources/views/User/index.html.twig
{# src/Najdah/UserBundle/Resources/views/User/index.html.twig #}

{% extends "NajdahUserBundle::layout.html.twig" %}

{% block title %}{{ type_user }}s - {{ parent() }}{% endblock %}

{% block menu_Policiers %}{% if type_user=='Policier' %}<span class="selected"></span>{% endif %}{% endblock %}
{% block menu_Pompiers %}{% if type_user=='Pompier' %}<span class="selected"></span>{% endif %}{% endblock %}
{% block menu_Policiers_active %}{% if type_user=='Policier' %}active{% endif %}{% endblock %}
{% block menu_Pompiers_active %}{% if type_user=='Pompier' %}active{% endif %}{% endblock %}

{% block javascripts %}
{{ parent() }}
<script src="{{ asset('assets/scripts/table_advanced_user.js') }}"></script>
{% endblock %}

{% block body_userBundle %}
<!-- BEGIN EXAMPLE TABLE PORTLET-->
<div class="portlet box green">
        <div class="portlet-title">
                <div class="caption"><i class="icon-globe"></i>Users</div>
                <div class="tools">
                        <a href="javascript:;" class="reload"></a>
                        <a href="javascript:;" class="remove"></a>
                </div>
        </div>
        <div class="portlet-body">
            <div class="table-toolbar">
                <div class="btn-group">
                    <button id="sample_editable_1_new" class="btn green"><a href="{{ path('user_ajouter', {'type_user': type_user}) }}">
                    Add New <i class="icon-plus"></i>
                    </a></button>
                </div>
                <div class="btn-group pull-right">
                    <button class="btn dropdown-toggle" data-toggle="dropdown">Tools <i class="icon-angle-down"></i>
                    </button>
                    <ul class="dropdown-menu pull-right">
                        <li><a href="#">Print</a></li>
                        <li><a href="#">Save as PDF</a></li>
                        <li><a href="#">Export to Excel</a></li>
                    </ul>
                </div>
            </div>
            <table class="table table-striped table-bordered table-hover table-full-width" id="sample_1">
                <thead>
                    <tr>
                        <th class="hidden">Image</th>
                        <th>Matricule</th>
                        <th>Nom</th>
                        <th>Tel</th>
                        <th class="hidden">Roles</th>
                        <th class="hidden">Lien</th>
                        <th>Actions</th>
                    </tr>
                </thead>
                <tbody>
                    {% for user in users %}
                        <tr>
                            <td class="hidden"><img style="height:100px;" src="{% if user.image == '' %}{{ asset( 'najdah/img/users/user.jpg' ) }}{% else %}{{ asset( user.webPath ) }}{% endif %}" class="img-circle img-thumbnail"/></td>
                            <td>{{ user.matricule }}</td>
                            <td>{{ user.nom }}</td>
                            <td>{{ user.tel }}</td>
                            <td class="hidden">{% for role in user.roles %}{{ role }} | {% endfor %}</td>
                            <td class="hidden"><a href="{{ path('user_roles', {'type_user': type_user,'id': user.id}) }}">Gestion des Roles.</a></td>
                            <td>
                                <a class="widget-icon widget-icon-circle" href="{{ path('user_modifier', {'type_user': type_user,'id': user.id}) }}" ><span class="icon-edit" /></a>
                                <a class="widget-icon widget-icon-circle" href="{{ path('user_supprimer', {'type_user': type_user,'id': user.id}) }}" ><span class="icon-remove-sign" /></a>
                            </td>
                        </tr>
                    {% else %}
                        <span>Pas (encore !) des users !!!</span>
                    {% endfor %}
                </tbody>
            </table>
        </div>
</div>
<!-- END EXAMPLE TABLE PORTLET-->

{#<td><img src="{% if user.image == '' %}{{ asset( 'template/img/user.jpg' ) }}{% else %}{{ asset( user.webPath ) }}{% endif %}" class="img-circle img-thumbnail"/> </td>#}
                        
{% endblock %}

{% block javascript_ready %}
{{ parent() }}
TableAdvanced.init();
{% endblock %}

src/Najdah/UserBundle/Resources/views/User/lastUser.html.twig
{# src/Najdah/UserBundle/Resources/views/User/lastUser.html.twig #}

src/Najdah/UserBundle/Resources/views/User/modifier.html.twig
{# src/Najdah/UserBundle/Resources/views/User/modifier.html.twig #}

{% extends "NajdahUserBundle::layout.html.twig" %}

{% block menu_Policiers %}{% if type_user=='Policier' %}<span class="selected"></span>{% endif %}{% endblock %}
{% block menu_Pompiers %}{% if type_user=='Pompier' %}<span class="selected"></span>{% endif %}{% endblock %}
{% block menu_Policiers_active %}{% if type_user=='Policier' %}active{% endif %}{% endblock %}
{% block menu_Pompiers_active %}{% if type_user=='Pompier' %}active{% endif %}{% endblock %}

{% block body_userBundle %}
    <h2>Modifier :</h2>
	
    {% include "NajdahUserBundle:User:formulaire.html.twig" %}
{% endblock %}

src/Najdah/UserBundle/Resources/views/User/roles.html.twig
{# src/Najdah/UserBundle/Resources/views/User/index.html.twig #}

{% extends "NajdahUserBundle::layout.html.twig" %}

{% block menu_Policiers %}{% if type_user=='Policier' %}<span class="selected"></span>{% endif %}{% endblock %}
{% block menu_Pompiers %}{% if type_user=='Pompier' %}<span class="selected"></span>{% endif %}{% endblock %}
{% block menu_Policiers_active %}{% if type_user=='Policier' %}active{% endif %}{% endblock %}
{% block menu_Pompiers_active %}{% if type_user=='Pompier' %}active{% endif %}{% endblock %}

{% block javascripts %}
{{ parent() }}
<script src="{{ asset('assets/scripts/form-components.js') }}"></script>
<script src="{{ asset('assets/plugins/bootstrap-switch/static/js/bootstrap-switch.js') }}" type="text/javascript" ></script>
{% endblock %}

{% block body_userBundle %}
<div class="row-fluid">
    <div class="span12">
        <!-- BEGIN PORTLET-->   
        <div class="portlet box blue">
            <div class="portlet-title">
                <div class="caption"><i class="icon-reorder"></i>Gestion des Roles :</div>
                <div class="tools">
                    <a href="javascript:;" class="collapse"></a>
                    <a href="#portlet-config" data-toggle="modal" class="config"></a>
                    <a href="javascript:;" class="reload"></a>
                    <a href="javascript:;" class="remove"></a>
                </div>
            </div>
            <div class="portlet-body form">
                <!-- BEGIN FORM-->
                <form action="{{ path('user_roles', {'type_user': type_user,'id': user.id}) }}" method="post" class="form-horizontal">

                    {% if is_granted('ROLE_ADMIN_POLICIER') %} 
                    <div class="control-group">
                        <label class="control-label">ROLE_POLICIER</label>
                        <div class="controls">
                            <div class="switch" data-on-label="<i class='icon-ok icon-white'></i>" data-off-label="<i class='icon-remove'></i>">
                                <input name="ROLE_POLICIER" type="checkbox" {% if user.hasRole('ROLE_POLICIER') %}  checked {% endif %} class="toggle"/>
                            </div>
                        </div>
                    </div>
                    {% endif %}
                    {% if is_granted('ROLE_ADMIN_POMPIER') %}
                    <div class="control-group">
                        <label class="control-label">ROLE_POMPIER</label>
                        <div class="controls">
                            <div class="switch" data-on-label="<i class='icon-ok icon-white'></i>" data-off-label="<i class='icon-remove'></i>">
                                <input name="ROLE_POMPIER" type="checkbox" {% if user.hasRole('ROLE_POMPIER') %}  checked {% endif %} class="toggle"/>
                            </div>
                        </div>
                    </div>
                    {% endif %}
                    {% if is_granted('ROLE_ADMIN') %}
                    <div class="control-group">
                        <label class="control-label">ROLE_ADMIN_POLICIER</label>
                        <div class="controls">
                            <div class="switch" data-on-label="<i class='icon-ok icon-white'></i>" data-off-label="<i class='icon-remove'></i>">
                                <input name="ROLE_ADMIN_POLICIER" type="checkbox" {% if user.hasRole('ROLE_ADMIN_POLICIER') %}  checked {% endif %} class="toggle"/>
                            </div>
                        </div>
                    </div>
                    {% endif %}
                    {% if is_granted('ROLE_ADMIN') %}
                    <div class="control-group">
                        <label class="control-label">ROLE_ADMIN_POMPIER</label>
                        <div class="controls">
                            <div class="switch" data-on-label="<i class='icon-ok icon-white'></i>" data-off-label="<i class='icon-remove'></i>">
                                <input name="ROLE_ADMIN_POMPIER" type="checkbox" {% if user.hasRole('ROLE_ADMIN_POMPIER') %}  checked {% endif %} class="toggle"/>
                            </div>
                        </div>
                    </div>
                    {% endif %}
                    {% if is_granted('ROLE_SUPER_ADMIN') %}
                    <div class="control-group">
                        <label class="control-label">ROLE_ADMIN</label>
                        <div class="controls">
                            <div class="switch" data-on-label="<i class='icon-ok icon-white'></i>" data-off-label="<i class='icon-remove'></i>">
                                <input name="ROLE_ADMIN" type="checkbox" {% if user.hasRole('ROLE_ADMIN') %}  checked {% endif %} class="toggle"/>
                            </div>
                        </div>
                    </div>
                    {% endif %}
                    {% if is_granted('ROLE_SUPER_ADMIN') %}
                    <div class="control-group">
                        <label class="control-label">ROLE_SUPER_ADMIN</label>
                        <div class="controls">
                            <div class="switch" data-on-label="<i class='icon-ok icon-white'></i>" data-off-label="<i class='icon-remove'></i>">
                                <input name="ROLE_SUPER_ADMIN" type="checkbox" {% if user.hasRole('ROLE_SUPER_ADMIN') %}  checked {% endif %} class="toggle"/>
                            </div>
                        </div>
                    </div>
                    {% endif %}

                    <div class="form-actions">
                        <button type="submit" class="btn blue">Submit</button>
                        <button type="button" class="btn">Cancel</button>     
                    </div>
                </form>

                <!-- END FORM-->  
            </div>
        </div>
        <!-- END PORTLET-->
    </div>
</div>
{% endblock %}

{% block javascript_ready %}
{{ parent() }}
FormComponents.init();
{% endblock %}